CC = g++
CC_FLAGS = -std=c++17 -w -O0

SRC_DIR = src/*.cpp

SCARLET_SRC_DIR += src/scarlet/core/*.cpp src/scarlet/core/logger/*.cpp src/scarlet/core/time/*.cpp src/scarlet/scene/*.cpp  
SCARLET_SRC_DIR += src/scarlet/graphics/*.cpp src/scarlet/graphics/buffer/*.cpp src/scarlet/graphics/camera/*.cpp 
SCARLET_SRC_DIR += src/scarlet/imgui/*.cpp src/scarlet/input/*.cpp src/scarlet/primitives/*.cpp src/scarlet/system/*.cpp src/scarlet/utils/*.cpp

SCARLET_EDITOR_SRC_DIR = src/scarletEditor/panels/*.cpp src/scarletEditor/*.cpp

VENDOR_SRC_DIR = vendor/Imgui/*.cpp

LINKER_FLAGS = -lmingw32 -lSDL2main -lSDL2_image -lSDL2 -lopengl32 -lglew32 -lImm32
BIN_NAME = ScarletEngine.exe

compile:
	$(CC) $(CC_FLAGS) $(SRC_DIR) $(SCARLET_SRC_DIR) $(SCARLET_EDITOR_SRC_DIR) $(VENDOR_SRC_DIR) -o build/$(BIN_NAME) -Ivendor -Iinclude -Llib  $(LINKER_FLAGS)
run:
	build/$(BIN_NAME)